  CREATE DATABASE db_jovesolides CHARACTER SET utf8 COLLATE utf8_general_ci;
USE DB_JOVESOLIDES;
CREATE TABLE USUARIO ( 
Id_usuario INT AUTO_INCREMENT,
  usuario VARCHAR(15),
  correo VARCHAR(150),
  contraseña VARCHAR(20),
PRIMARY KEY(Id_usuario),
UNIQUE KEY CORREO (correo)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA USUARIO';
CREATE TABLE SEXO
(Id_Sexo INT auto_increment,
Nombre	VARCHAR(10),
PRIMARY KEY(Id_Sexo)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA SEXO';

CREATE TABLE ESTADO
(Id_Estado INT auto_increment,
Nombre VARCHAR(20),
PRIMARY KEY(Id_Estado)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA ESTADO';

CREATE TABLE ASOCIADOS
(Id_Asociado INT AUTO_INCREMENT,
nombre VARCHAR(80),
apellido VARCHAR(80),
dui VARCHAR(10),
Id_Estado INT,
SocioFundador CHAR(2),
PRIMARY KEY (Id_Asociado),
UNIQUE KEY DUI (dui),
FOREIGN KEY (Id_Estado) REFERENCES ESTADO(Id_Estado)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA ASOCIADO';

CREATE TABLE PATROCINADOR
(Id_Patrocinador INT AUTO_INCREMENT,
nombre VARCHAR(30),
NIT VARCHAR(17),
direccion VARCHAR(200),
PRIMARY KEY(Id_Patrocinador),
UNIQUE KEY NIT (NIT)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA PATROCINADOR';

CREATE TABLE BECA
( Id_Beca INT AUTO_INCREMENT,
Id_Patrocinador INT,
Id_Estado INT,
Fecha_Ingreso DATE,
Fecha_Egreso DATE,
PRIMARY KEY(Id_Beca),
FOREIGN KEY (Id_Patrocinador) REFERENCES PATROCINADOR(Id_Patrocinador),
FOREIGN KEY (Id_Estado) REFERENCES ESTADO(Id_Estado)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA BECA';
CREATE TABLE UNIVERSIDAD
( Id_Universidad INT AUTO_INCREMENT,
Nombre VARCHAR(40),
PRIMARY KEY(Id_Universidad)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA UNIVERSIDAD';

CREATE TABLE CARRERA
( Id_Carrera INT AUTO_INCREMENT,
Nombre VARCHAR(50),
PRIMARY KEY(Id_Carrera)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA CARRERA';

CREATE TABLE FORMACION_ACADEMICA
(Id_estudio INT AUTO_INCREMENT,
Id_Universidad INT,
Id_Carrera INT,
Fecha_Grad DATE,
PRIMARY KEY(Id_estudio),
FOREIGN KEY (Id_Universidad) REFERENCES UNIVERSIDAD(Id_Universidad),
FOREIGN KEY (Id_Carrera) REFERENCES CARRERA(Id_Carrera)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA FORMACION_ACADEMINCA';

CREATE TABLE DEPARTAMENTO
(Id_Departamento INT AUTO_INCREMENT,
Nombre VARCHAR(20),
PRIMARY KEY(Id_Departamento),
UNIQUE KEY NOMBRE(Nombre)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA DEPARTAMENTO';

CREATE TABLE MUNICIPIO 
(Id_Municipio INT AUTO_INCREMENT,
Nombre VARCHAR(30),
Id_Departamento INT,
PRIMARY KEY(Id_Municipio),
FOREIGN KEY (Id_Departamento) REFERENCES DEPARTAMENTO(Id_Departamento)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA MUNICIPIO';

CREATE TABLE TRABAJO
(Id_Trabajo INT AUTO_INCREMENT,
nombre VARCHAR(50),
Id_Departamento INT,
PRIMARY KEY(Id_Trabajo),
FOREIGN KEY (Id_Departamento) REFERENCES DEPARTAMENTO(Id_Departamento)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA TRABAJO';

CREATE TABLE BECARIO
( Id_Becario INT AUTO_INCREMENT,
Id_estudio INT,
Id_Beca INT,
Id_Trabajo INT,
Fotografia VARCHAR(200),
Nombres VARCHAR(30),
Apellidos VARCHAR(40),
Id_Sexo INT,
Correo VARCHAR(150),
Telefono INT,
Id_Departamento INT,
Id_Municipio INT,
Observacion VARCHAR(200),
PRIMARY KEY(Id_Becario),
FOREIGN KEY (Id_estudio) REFERENCES FORMACION_ACADEMICA(Id_estudio),
FOREIGN KEY (Id_Beca) REFERENCES BECA(Id_Beca),
FOREIGN KEY (Id_Trabajo) REFERENCES TRABAJO(Id_Trabajo),
FOREIGN KEY (Id_Departamento) REFERENCES DEPARTAMENTO(Id_Departamento),
FOREIGN KEY (Id_Municipio) REFERENCES MUNICIPIO(Id_Municipio),
FOREIGN KEY (Id_Sexo) REFERENCES SEXO(Id_Sexo),
UNIQUE KEY CORREO(correo) )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA BECARIO';

CREATE TABLE EXPEDIENTE
(Id_Expediente INT AUTO_INCREMENT,
Id_Becario INT,
PRIMARY KEY(Id_Expediente),
FOREIGN KEY (Id_Becario) REFERENCES BECARIO(Id_Becario),
UNIQUE KEY BECARIO(Id_Becario)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TABLA EXPEDIENTE';






















